### PR TITLE
nmea: add ability to send output via socat

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by stephendade** [comment]
From the rules:
NMEA over Ethernet
• 100Base-T Fast Ethernet connection
• Server socket accepting connections and sending NMEA strings
• Statically addressed
• Address, netmask and port must be configurable at the event
For either physical interface the data will be received by a computer running GPSD version 3.17.
http://www.catb.org/gpsd/

Would be worth testing with gpsd...

**Comment by peterbarker** [comment]
On Thu, 16 Aug 2018, Stephen wrote:

> From the rules:
> NMEA over Ethernet
> • 100Base-T Fast Ethernet connection
> • Server socket accepting connections and sending NMEA strings
> • Statically addressed
> • Address, netmask and port must be configurable at the event
> For either physical interface the data will be received by a computer running GPSD version 3.17.
> http://www.catb.org/gpsd/

Is that all?  Because "connection" hints at TCP, not UDP.... *sigh*

I'll test against gpsd, thanks.

**Comment by stephendade** [comment]
>Is that all?  Because "connection" hints at TCP, not UDP.... *sigh*

That's all I could find in the rules document (Section 3.2.3)

**Comment by peterbarker** [comment]
`gpsd -D 10  udp://127.0.0.1:4567 -N -n`

`nmea udp:127.0.0.1:4567`

`nmea socat:UDP-SENDTO:127.0.0.1:4567`

**Comment by peterbarker** [comment]
`nmea log:/tmp/fnoo.nmea`

Put log in the aircraft directory: `nmea log:fnoo.nmea`

**Pull request merged**
