### PR TITLE
Random stuff

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
I've tested this and it works a-ok.

**Comment by rmackay9** [comment]
I've tested the updated patches and I've found:

- "add delta-time in output" works well.
- right-mouse-button clicking on an item in the Mosaic and selecting, "Show Image" (or double clicking on the image in the Mosaic) brought up the window but an error was displayed in the console, "AttributeError: MPImage instance has no attribute 'center'.

As a side note (not related to this PR) but I notice the "Place Marker" is still not quite accurate.  It should be that if I use the Image Viewer and click within the blue box and then select "Place Marker", the marker should appear right on the blue box in the main map view.  Maybe there's a lat/lon scaling issue or something.  I'm not sure but it doesn't seem that it's internally consistent somehow.

**Comment by peterbarker** [comment]
On Thu, 28 Sep 2017, Randy Mackay wrote:

>     the window but an error was displayed in the console, "AttributeError:
>     MPImage instance has no attribute 'center'.

Were you using my "wx3" branch of MAVProxy?

**Comment by rmackay9** [comment]
@peterbarker, ok, i'll retry with the wx3 branch of MAVProxy.

**Pull request merged**
